Align gradle with maven plugin
flock-community/wirespec pull request #223
Opened 2024-05-28 19:11 UTC by wilmveel

2024-06-08 11:17 UTC, sjorsdev approved these changes

2024-06-09 16:52 UTC, jerrevanveluw requested changes
If the only thing you are adding is the custom emitter, we should include that in the main ktor example. Then that example has just one more emitter...

2024-06-09 16:52 UTC, jerrevanveluw commented on src/plugin/gradle/src/main/kotlin/WirespecPlugin.kt
> +    private fun List<Emitted>.writeFiles() = this
Why return `this`?

2024-06-09 16:52 UTC, jerrevanveluw commented on src/plugin/gradle/src/main/kotlin/WirespecPlugin.kt
> +                        KotlinShared
Should be ScalaShared

2024-06-09 16:52 UTC, jerrevanveluw commented on src/plugin/gradle/src/main/kotlin/WirespecPlugin.kt
> +                        KotlinShared
Should be null or TypeScriptShared

2024-06-09 16:52 UTC, jerrevanveluw commented on src/plugin/gradle/src/main/kotlin/WirespecPlugin.kt
> +                            KotlinShared
Should be null or WirespecShared

2024-06-10 11:03 UTC, wilmveel commented on src/plugin/gradle/src/main/kotlin/WirespecPlugin.kt
> +    private fun List<Emitted>.writeFiles() = this
Function was never used

2024-06-14 14:43 UTC, jerrevanveluw approved these changes

2024-06-14 15:03 UTC, merged